// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ilk.Models;

namespace ilk.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230530133017_a")]
    partial class a
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ilk.Models.Departman", b =>
                {
                    b.Property<int>("departman_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("departman_adi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departman_id");

                    b.ToTable("Departmans");
                });

            modelBuilder.Entity("ilk.Models.Personel", b =>
                {
                    b.Property<int>("personel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("departman_id")
                        .HasColumnType("int");

                    b.Property<string>("personel_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personel_sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personel_soyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personel_id");

                    b.HasIndex("departman_id");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("ilk.Models.Personel", b =>
                {
                    b.HasOne("ilk.Models.Departman", "Departman")
                        .WithMany("Personels")
                        .HasForeignKey("departman_id");
                });
#pragma warning restore 612, 618
        }
    }
}
