// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ilk.Models;

namespace ilk.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ilk.Models.Departman", b =>
                {
                    b.Property<int>("departman_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("departman_adi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departman_id");

                    b.ToTable("departmans");
                });

            modelBuilder.Entity("ilk.Models.Personel", b =>
                {
                    b.Property<int>("personel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("personel_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personel_sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personel_soyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personel_id");

                    b.ToTable("personels");
                });
#pragma warning restore 612, 618
        }
    }
}
